envVarGroups:
  - name: app-exam-env

services:
  - name: gateway
    type: web
    runtime: node
    rootDir: ./gateway
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVarGroups:
      - app-exam-env
    envVars:
      - key: PORT
        value: 10000

  - name: backend
    type: web
    runtime: node
    rootDir: ./backend
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVarGroups:
      - app-exam-env
    envVars:
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true

  - name: notifications
    type: web
    runtime: node
    rootDir: ./microservices/notifications
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVarGroups:
      - app-exam-env
    envVars:
      - key: PORT
        value: 10000

  - name: stock-management
    type: web
    runtime: node
    rootDir: ./microservices/stock-management
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVarGroups:
      - app-exam-env
    envVars:
      - key: PORT
        value: 10000

  - name: frontend
    type: web
    runtime: static
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVarGroups:
      - app-exam-env
    envVars:
      - key: REACT_APP_GATEWAY_URL
        sync: false
      - key: REACT_APP_BACKEND_URL
        sync: false